{% set name = "svmbir" %}
{% set version = "0.3.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://test-files.pythonhosted.org/packages/6d/99/94b94ee6135ff05ee82282e0cbfba0eeccb91ccc5386ab18a318d6e1be04/{{ name }}-{{ version }}.tar.gz
  sha256: 594280f6af6270b41643871a41fd4d1b0ceeb69a6a2fcec50bb563cf8749818d

build:
  number: 0
  skip: true  # [win or py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - pip
    - python
    - numpy =1.21.6
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  run:
    - llvm-openmp  # [osx]
    - pillow >=9.1,<=9.3
    - psutil >=5.8
    - python
    - numpy >=1.21.4
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - svmbir
  commands:
    - pip check
    - pytest
  requires:
    - pip
    - pytest
  source_files:
    - svmbir/tests/*

about:
  home: https://github.com/cabouman/svmbir
  summary: Python code for fast MBIR (Model Based Iterative Reconstruction)
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bwohlberg
    - sjkisner
    - gbuzzard
    - cabouman
